package ru.roskazna.gisgmp._02000000.smevgisgmpservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2017-11-22T00:04:44.674+03:00
 * Generated source version: 3.1.14
 * 
 */
@WebService(targetNamespace = "http://roskazna.ru/gisgmp/02000000/SmevGISGMPService/", name = "SmevGISGMPService")
@XmlSeeAlso({ru.roskazna.gisgmp.xsd._116.budgetindex.ObjectFactory.class, ru.roskazna.gisgmp.xsd._116.ticket.ObjectFactory.class, ru.roskazna.gisgmp.xsd._116.errinfo.ObjectFactory.class, ru.roskazna.gisgmp.xsd._116.chargecreationrequest.ObjectFactory.class, ru.roskazna.gisgmp.xsd._116.charge.ObjectFactory.class, org.w3._2004._08.xop.include.ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, ru.roskazna.gisgmp.xsd._116.paymentinfo.ObjectFactory.class, ru.roskazna.gisgmp.xsd._116.common.ObjectFactory.class, ru.roskazna.gisgmp.xsd._116.pgu_importrequest.ObjectFactory.class, ru.roskazna.gisgmp.xsd._116.doacknowledgment.ObjectFactory.class, ru.roskazna.gisgmp.xsd._116.selfadministration.ObjectFactory.class, ObjectFactory.class, ru.roskazna.gisgmp.xsd._116.organization.ObjectFactory.class, ru.roskazna.gisgmp.xsd._116.messagedata.ObjectFactory.class, ru.roskazna.gisgmp.xsd._116.quittance.ObjectFactory.class, ru.roskazna.gisgmp.xsd._116.pgu_datarequest.ObjectFactory.class, ru.roskazna.gisgmp.xsd._116.exportquittanceresponse.ObjectFactory.class, ru.roskazna.gisgmp.xsd._116.packagestatusrequest.ObjectFactory.class, ru.roskazna.gisgmp.xsd._116.chargecreationresponse.ObjectFactory.class, ru.gosuslugi.smev.rev120315.ObjectFactory.class, ru.roskazna.gisgmp.xsd._116.message.ObjectFactory.class, ru.roskazna.gisgmp.xsd._116.pgu_chargesresponse.ObjectFactory.class, ru.roskazna.gisgmp.xsd._116.exportpaymentsresponse.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SmevGISGMPService {

    @WebResult(name = "GISGMPTransferMsg", targetNamespace = "http://roskazna.ru/gisgmp/02000000/SmevGISGMPService/", partName = "outputmsg")
    @WebMethod(operationName = "GISGMPTransferMsg", action = "http://roskazna.ru/gisgmp/02000000/SmevGISGMPService/GISGMPTransferMsg")
    public ru.gosuslugi.smev.rev120315.BaseMessageType gisgmpTransferMsg(
        @WebParam(partName = "inputmsg", name = "GISGMPTransferMsg", targetNamespace = "http://roskazna.ru/gisgmp/02000000/SmevGISGMPService/")
        ru.gosuslugi.smev.rev120315.BaseMessageType inputmsg
    );
}
