package ru.roskazna.gisgmp._02000000.smevgisgmpservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2017-11-22T00:04:44.740+03:00
 * Generated source version: 3.1.14
 * 
 */
@WebServiceClient(name = "SmevGISGMPService", 
                  wsdlLocation = "http://smev-mvf.test.gosuslugi.ru:7777/gateway/services/SID0003663/1.00/wsdl",
                  targetNamespace = "http://roskazna.ru/gisgmp/02000000/SmevGISGMPService/") 
public class SmevGISGMPService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://roskazna.ru/gisgmp/02000000/SmevGISGMPService/", "SmevGISGMPService");
    public final static QName SmevGISGMPServiceSOAP = new QName("http://roskazna.ru/gisgmp/02000000/SmevGISGMPService/", "SmevGISGMPServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://smev-mvf.test.gosuslugi.ru:7777/gateway/services/SID0003663/1.00/wsdl");//"file:C:/gisgmp/SmevGISGMPService.wsdl"
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SmevGISGMPService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:SmevGISGMPService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SmevGISGMPService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SmevGISGMPService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SmevGISGMPService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SmevGISGMPService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SmevGISGMPService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SmevGISGMPService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SmevGISGMPService
     */
    @WebEndpoint(name = "SmevGISGMPServiceSOAP")
    public SmevGISGMPService getSmevGISGMPServiceSOAP() {
        return super.getPort(SmevGISGMPServiceSOAP, SmevGISGMPService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SmevGISGMPService
     */
    @WebEndpoint(name = "SmevGISGMPServiceSOAP")
    public SmevGISGMPService getSmevGISGMPServiceSOAP(WebServiceFeature... features) {
        return super.getPort(SmevGISGMPServiceSOAP, SmevGISGMPService.class, features);
    }

}
