org.apache.ws.security.crypto.provider=wss4j.wss4j1_6.ws.security.components.crypto.MerlinEx
org.apache.ws.security.crypto.merlin.keystore.type=HDImageStore
org.apache.ws.security.crypto.merlin.keystore.password=1
org.apache.ws.security.crypto.merlin.keystore.alias=GisSignContainer
cert.file=C:/merlin/keys/my/gost_exch/client.cer
ca.file=C:/merlin/keys/my/ca.cer
crl.file=C:/merlin/keys/my/certcrl.crl