<?xml version="1.0" encoding="UTF-8"?>
<!--suppress ALL -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ru.cryptopro</groupId>
        <artifactId>jcp-parent</artifactId>
        <version>2.0.49800-A</version>
    </parent>

    <artifactId>jcp-samples</artifactId>
    <packaging>jar</packaging>

    <description>Original samples of code from JCP distribution</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
    </properties>


    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>ru.cryptopro</groupId>
                <artifactId>jcp-bom</artifactId>
                <version>2.0.49800-A</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>ru.cryptopro.jcp</groupId>
            <artifactId>cpssl</artifactId>
        </dependency>

        <dependency>
            <groupId>ru.cryptopro.jcp</groupId>
            <artifactId>jcp</artifactId>
        </dependency>

        <dependency>
            <groupId>ru.cryptopro.jcp</groupId>
            <artifactId>jcryptop</artifactId>
        </dependency>

        <dependency>
            <groupId>ru.cryptopro.jcsp</groupId>
            <artifactId>jcsp</artifactId>
        </dependency>

        <dependency>
            <groupId>ru.cryptopro.jcp</groupId>
            <artifactId>jcprevcheck</artifactId>
        </dependency>

        <dependency>
            <groupId>ru.cryptopro.jcp</groupId>
            <artifactId>jcpxml</artifactId>
        </dependency>

        <dependency>
            <groupId>ru.cryptopro.jcp</groupId>
            <artifactId>jcprequest</artifactId>
        </dependency>

        <dependency>
            <groupId>ru.cryptopro.jcp</groupId>
            <artifactId>cades</artifactId>
        </dependency>

        <dependency>
            <groupId>ru.cryptopro.jcp</groupId>
            <artifactId>xades</artifactId>
        </dependency>

        <dependency>
            <groupId>ru.cryptopro.jcp</groupId>
            <artifactId>rutoken</artifactId>
        </dependency>


<!--  utils -->

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.5.32</version>
        </dependency>


        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>jul-to-slf4j</artifactId>
            <version>2.0.17</version>
        </dependency>

        <dependency>
            <groupId>commons-logging</groupId>
            <artifactId>commons-logging</artifactId>
            <version>1.2</version>
        </dependency>

        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk18on</artifactId>
            <version>1.78.1</version>
        </dependency>

        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.14</version>
        </dependency>

        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpasyncclient</artifactId>
            <version>4.1.5</version>
        </dependency>

        <dependency>
            <groupId>com.github.ljun20160606</groupId>
            <artifactId>okhttp</artifactId>
            <version>3.10.0</version>
        </dependency>

        <dependency>
            <groupId>xalan</groupId>
            <artifactId>xalan</artifactId>
            <version>2.7.3</version>
        </dependency>

        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>itextpdf_patched</artifactId>
        </dependency>

<!--
        <dependency>
            <groupId>org.apache.geronimo.bundles</groupId>
            <artifactId>axis</artifactId>
            <version>1.4_2</version>
        </dependency>
-->
        <dependency>
            <groupId>com.liferay</groupId>
            <artifactId>org.apache.axis</artifactId>
            <version>1.4.LIFERAY-PATCHED-8</version>
        </dependency>

        <dependency>
            <groupId>com.sun.xml.ws</groupId>
            <artifactId>webservices-rt</artifactId>
            <version>2.1-b16</version>
        </dependency>

        <dependency>
            <groupId>org.apache.ws.security</groupId>
            <artifactId>wss4j</artifactId>
            <version>1.6.19</version>
        </dependency>

        <dependency>
            <groupId>com.googlecode.xades4j</groupId>
            <artifactId>xades4j</artifactId>
            <version>1.3.1</version>
        </dependency>

        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-frontend-simple</artifactId>
            <version>4.2.0</version>
        </dependency>

        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-ws-security</artifactId>
            <version>4.2.0</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.1</version>
                <configuration>
                    <compilerArgs>
                        <arg>-Xlint:none</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>